import type { Metadata } from "next";
import { Lato ,Corben} from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";

const lato = Lato({
  subsets: ['latin'],
  weight: ["100", "300", "400", "700", "900"], 
  variable: '--font-lato',
});

const corben = Corben({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-corben', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${corben.variable}  antialiased`}
      >
        <CartProvider>
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
